### PR TITLE
Minor README file update

### PR DESCRIPTION
**Pull request by tremes**
# Description
 Minor update of the `README` file

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Documentation update

## Testing steps

Follow the README file steps.

## Checklist
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary

### CODE REVIEW

**Comment by tremes** [comment]
I suspect that this https://github.com/RedHatInsights/insights-operator-gathering-conditions-service/pull/156/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R146 might be wrong as well, but I was not able to run the container due to the (and I don't have time to investigate it):
```
/insights-operator-gathering-conditions-service: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /insights-operator-gathering-conditions-service)
/insights-operator-gathering-conditions-service: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /insights-operator-gathering-conditions-service)

```

**Review by tisnik — APPROVED** [review]
LGTM

**Comment by juandspy** [comment]
> I suspect that [this](https://github.com/RedHatInsights/insights-operator-gathering-conditions-service/blob/main/README.md?plain=1#L134) might be wrong as well, but I was not able to run the container due to the (and I don't have time to investigate it):
> 
> ```
> /insights-operator-gathering-conditions-service: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /insights-operator-gathering-conditions-service)
> /insights-operator-gathering-conditions-service: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /insights-operator-gathering-conditions-service)
> ```

hey @tremes . This was happening to some of us some days ago with other repos. It's probably because the binary was build in a different system than the one you are using. It happened to us when building a docker image with a binary in the root path where the image copied the files from.

**Review by juandspy — APPROVED** [review]
LGTM btw :)

**Pull request merged**
